version: "3.7"
services:

  db:
    image: mariadb:10
    container_name: wpgains-experiments-db
    restart: always    
    ports: ['8083:3306']
    volumes:      
      #- ./mysql/data:/var/lib/mysql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  
  wordpress:
    image: wordpress:5
    container_name: wpgains-experiments-wp
    restart: always
    links: ['db']
    depends_on: ['db']
    ports: ['8000:80']
    volumes:
      - ./mounts/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db      
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: wp_

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        PMA_HOST: db
      ports:
        - 8082:80
volumes:
    db_data: