version: "3.7"
services:
 
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    container_name: wpgains-experiments-wp-fpm
    restart: always
    links: ['db']
    depends_on: ['db']
    ports: ['9000:9000']
    volumes:
      - ./mounts/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: wp_      

  nginx:
    image: nginx:stable
    container_name: wpgains-experiments-wp-nginx
    ports: ['8001:80']
    links: ['wordpress-fpm']
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./mounts/www:/var/www/html
      